name: promote-to-production (deprecated)

on:
  workflow_dispatch:
    inputs:
      note:
        description: 'This workflow is deprecated; deploy happens automatically after staging.'
        required: false

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Production deploy is automatic in ci-cd.yml. This workflow remains only for reference."


